### ISSUE TITLE
Dr. Memory tool does not work on 64-bit systems.

### ISSUE THREAD

**Issue by tzapzoor** [rosedu/robocheck#17]
To compile C code in 32-bit, additional libraries must be installed.

**Comment by lauravasilescu** [comment]
Did you identify the libraries?

**Comment by tzapzoor** [comment]
"gcc -m32" seems to work with g++-multilib and libc6-dev-i386 (Debian/Ubuntu).
Another problem could appear, though. All the sources tested with Dr. Memory should be compiled with the "-m32" flag. That means that every Makefile should be written in this manner.

**Comment by lauravasilescu** [comment]
Hm... I had the impression that dr. memory also has support for 64-bit application, but I checked on their website and it says that "Dr. Memory currently targets 32-bit applications only". So I guess this is not a bug in Robocheck.
However, Robocheck should check if the system/application is 32-bit before enabling this tool.

**Comment by tzapzoor** [comment]
Well, I guess that checking the application beforehand solves this problem :+1:

**Comment by tzapzoor** [comment]
Fixed.
